<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getDataSet</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoNCkRhdGFzZXRDb25maWd1cmF0aW9uIGN1c3RvbWVyQ29uZmlnID0NCgkJZGF0YXNldE1hbmFn
ZXIuZGF0YXNldENvbmZpZ3VyYXRpb24oKSAvLyA8Mz4NCgkJLm9mZmhlYXAoInNlY29uZCIpIC8v
IDw0Pg0KCQkuZGlzaygiY3VzdG9tZXIiKQ0KCQkuaW5kZXgoRk5BTUUsICBJbmRleFNldHRpbmdz
LkJUUkVFKS8vIDw1Pg0KCQkuaW5kZXgoTE5BTUUsSW5kZXhTZXR0aW5ncy5CVFJFRSkNCgkJLmlu
ZGV4KE1QSE9ORSxJbmRleFNldHRpbmdzLkJUUkVFKQ0KCQkuYnVpbGQoKTsgLy8gPDY+DQoNCiov
DQoNCg0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7DQoJU3RyaW5nCWRhdGFTZXROYW1lID0gSURhdGFVdGlsLmdldFN0cmluZygg
cGlwZWxpbmVDdXJzb3IsICJkYXRhU2V0TmFtZSIgKTsNCg0KLy8gcGlwZWxpbmUNCg0KDQoNCglw
aXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoJ</value>
</Values>
