<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getRecordCount</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlkYXRhU2V0TmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiZGF0
YVNldE5hbWUiICk7DQpPcHRpb25hbDxTdHJpbmc+IGZpcnN0TmFtZV8xID0gT3B0aW9uYWwub2ZO
dWxsYWJsZShJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImZpcnN0TmFtZSIg
KSk7DQpPcHRpb25hbDxTdHJpbmc+IGxhc3ROYW1lXzEgPSAgT3B0aW9uYWwub2ZOdWxsYWJsZShJ
RGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImxhc3ROYW1lIiApKTsNCk9wdGlv
bmFsPFN0cmluZz5tb2JpbGVQaG9uZV8xID0gIE9wdGlvbmFsLm9mTnVsbGFibGUoSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJtb2JpbGVQaG9uZSIgKSk7DQoNCg0KDQovLyBw
aXBlbGluZQ0KDQp0cnkgIHsNCgkNCglEYXRhc2V0PFN0cmluZz4gZHMgPSBnZXREYXRhc2V0KCk7
DQoJRGF0YXNldFdyaXRlclJlYWRlcjxTdHJpbmc+IHdyaXRlclJlYWRlciA9IGRzLndyaXRlclJl
YWRlcigpOw0KCQ0KCQlsb25nIGNvbiA9IA0KCQkJCQkJd3JpdGVyUmVhZGVyLnJlY29yZHMoKQ0K
CQkJCS5leHBsYWluKFN5c3RlbS5vdXQ6OnByaW50bG4pIC8vIDwxPg0KCQkJCS5jb3VudCgpOwkJ
DQoJDQoJCXBpcGVsaW5lQ3Vyc29yLmluc2VydEFmdGVyKCJjb3VudCIsY29uKTsNCgkNCn1jYXRj
aChFeGNlcHRpb24gZSl7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdl
KCkpOw0KfQ0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
